"""My first DB migrate

Revision ID: 429e69932a43
Revises: 
Create Date: 2023-03-26 13:30:58.191744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429e69932a43'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortener',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('shortUrl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortener')
    # ### end Alembic commands ###
